project:
  type: website
  output-dir: docs

website:
  title: "Kelbi Hall"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
  page-footer:
    left: "© 2025 Kelbi Hall. All rights reserved."
    right: "Built with Quarto & GitHub Pages"

format:
  html:
    theme: flatly
    css: styles.css
