project:
  type: website
  output-dir: docs

website:
  title: "Kelbihall"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
    right:
      - text: Contact
        menu:
          - href: mailto:kelbi.hall@example.com
            text: Email
          - href: https://github.com/Kelbihall
            text: GitHub
          - href: https://linkedin.com/in/kelbihall
            text: LinkedIn
  page-footer:
    left: "© 2025 Kelbi Hall. All rights reserved."
    right: "Built with Quarto & GitHub Pages"

format:
  html:
    theme: minty
    css: styles.css  # We will use a simple CSS file
