---
title: "Projects"
---

---
title: "Projects"
format: html
---

# My Projects

## **PATCHWORK INITIATIVE**

-   As Co-Coordinator, I organize workshops, events, and campaigns that educate students on ethical fashion, textile recycling, and sustainable garment choices. My work involves developing strategies to reduce textile waste, advocate for circular economy principles in the fashion industry, and encourage long-term adoption of sustainable fashion practices by integrating industry trends and research into campus activities.

## **ZERO WASTE TEAM**

-   As the Communications Officer for the Zero Waste Team at Colorado State University, I, along with my fellow students, have spearheaded a number of initiatives aimed at promoting sustainable practices in the clothing industry including; mending meetings clothing swaps, and informational presentations.

## **SUSTAINABLE COTTON PRODUCTION RESEARCH PAPER**

-   During my coursework at Colorado State University I had the option to write a 10 page research paper on any topic and I developed a detailed report on sustainable cotton production, evaluating its environmental and economic impacts. The report highlights the significant issues with conventional cotton farming, such as excessive water usage, pesticide pollution, and soil degradation, while proposing solutions like organic cotton and the Better Cotton Initiative. These methods offer promising reductions in water consumption, pesticide use, and carbon emissions. Through this project, I examined the balance between environmental sustainability and economic feasibility, advocating for incremental implementation of sustainable practices to benefit both the environment and long-term industry economics.

------------------------------------------------------------------------

**Download my [full Project (PDF)](files/project.pdf)**
