---
title: "Resume"
format: html
---

# Kelbi Hall

Kelbi Hall Fort Collins, CO • Kelbi.Hall\@gmail.com • 214-455-1624 • www.linkedin.com/in/kelbihall

### EDUCATION

Bachelor of Science in Ecosystem Science and Sustainability

Minor in Merchandising Colorado State University – Fort Collins, CO

Expected Graduation: May 2026

**Relevant Coursework:** August 2022 – May 2024 Merchandising Processes, Sustainability Science, Fashion Industries,\
Textiles and Apparel Supply Chains, and Information Management for Sustainability

### UNIVERSITY INVOLVEMENT

**Co-Coordinator, Patchwork Initiative**

-   Lead campus initiatives promoting sustainable fashion

-   Manage workshops and educational events

September 2024 – Present

**Zero Waste Team Officer**

-   Perform waste audits for student events

-   Educational campaigns on sustainable practices

August 2023 – Present

**Fashion Group International Member**

-   Engage with a global network of fashion professionals

-   Follow industry trends, challenges and technologies

September 2024 – Present

**Rams Textile Society** **Member**

-   Observe innovations in textile science and product development

-   Experiment with textile testing and design through workshops

September 2024 – Present

### EXPERIENCE

**Student Photographer and Sustainability Media Specialist**

Colorado State University Housing and Dining

Fort Collins, CO August 2023 – Present

-   Self-sufficiently produce photo and video content to promote university housing and dining services, focusing on sustainability initiatives.

-   Collaborate with university sustainability and marketing teams to promote university initiatives.

    **Kelbi Hall Photography**

    Freelance

    Fort Collins, CO and Dallas, TX May 2019 – Present

-   Operate a full-service photography business specializing in events, portraits, and client-driven projects.

-   Manage client relationships with smooth communication and dependability.

### SKILLS

• Microsoft Suite • Data Analysis • Adobe Creative Cloud • Project Management

**Download my [full resume (PDF)](files/Resume.pdf)**
